CREATE DATABASE IF NOT EXISTS estoque CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE estoque;

CREATE TABLE posicao (
  id INT AUTO_INCREMENT PRIMARY KEY,
  rua TINYINT NOT NULL CHECK (rua BETWEEN 1 AND 14),
  prateleira TINYINT NOT NULL CHECK (prateleira BETWEEN 1 AND 4),
  coluna TINYINT NOT NULL CHECK (coluna BETWEEN 1 AND 18),
  UNIQUE KEY uk_pos (rua, prateleira, coluna)
);

CREATE TABLE caixa (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(64) NOT NULL,
  descricao VARCHAR(255) NULL,
  quantidade INT NOT NULL DEFAULT 1,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ocupacao (
  id INT AUTO_INCREMENT PRIMARY KEY,
  posicao_id INT NOT NULL,
  caixa_id INT NOT NULL,
  slot TINYINT NOT NULL CHECK (slot BETWEEN 1 AND 3),
  UNIQUE KEY uk_pos_slot (posicao_id, slot),
  FOREIGN KEY (posicao_id) REFERENCES posicao(id) ON DELETE CASCADE,
  FOREIGN KEY (caixa_id) REFERENCES caixa(id) ON DELETE CASCADE
);

INSERT INTO posicao (rua, prateleira, coluna)
SELECT r.n, p.n, c.n
FROM (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14) r,
     (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4) p,
     (SELECT 1 n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18) c;
